[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "parenteral-nutrition-tpn-engine"
version = "2.0.0"
description = "TPN-Prescriber: Total Parenteral Nutrition (TPN) Macro/Micro & Refeeding Engine"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
parenteral-nutrition-tpn-engine = "parenteral_nutrition_tpn_agent.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/parenteral-nutrition-tpn-engine"
Repository = "https://github.com/abusuraihsakhri/parenteral-nutrition-tpn-engine.git"
